# Generated by Django 2.1.3 on 2018-11-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_marca', models.PositiveIntegerField(default=1, unique=True)),
                ('nm_marca', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nm_marca'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_produto', models.PositiveIntegerField(default=1, unique=True)),
                ('nm_produto', models.CharField(max_length=255, unique=True)),
                ('dc_modelo', models.CharField(max_length=64)),
                ('cd_barras', models.CharField(max_length=15)),
                ('cd_altura', models.DecimalField(decimal_places=8, max_digits=15)),
                ('nr_comprimento', models.DecimalField(decimal_places=8, max_digits=15)),
                ('nr_largura', models.DecimalField(decimal_places=8, max_digits=15)),
                ('nr_peso', models.DecimalField(decimal_places=8, max_digits=15)),
                ('dt_cadastro', models.DateField(auto_now_add=True)),
                ('hr_cadastro', models.TimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateField(auto_now=True)),
                ('hr_alteracao', models.TimeField(auto_now=True)),
                ('dt_preco', models.DateField(auto_now=True)),
                ('hr_preco', models.TimeField(auto_now=True)),
                ('fl_situacao', models.PositiveIntegerField(default=1)),
                ('qt_estoque', models.DecimalField(decimal_places=4, max_digits=15)),
                ('vl_preco', models.DecimalField(decimal_places=4, max_digits=15)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Filial')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_variacao', models.PositiveIntegerField(default=1)),
                ('dc_cor', models.PositiveIntegerField(default=1)),
                ('dc_numero', models.PositiveIntegerField(default=1)),
                ('dc_voltagem', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Produto')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Variacao')),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
