# Generated by Django 2.1.3 on 2018-11-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cliente_eco', models.PositiveIntegerField(help_text='Código do cliente no e-commerce')),
                ('cd_cliente_erp', models.PositiveIntegerField(help_text='Código do cliente no ERP')),
                ('nr_cpf', models.CharField(default='', help_text='CPF', max_length=11)),
                ('nr_cnpj', models.CharField(default='', help_text='CNPJ', max_length=14)),
                ('nm_cliente', models.CharField(help_text='Nome/Fantasia do cliente', max_length=128)),
                ('dt_nascimento', models.DateField(blank=True, help_text='Data de nascimento', null=True)),
                ('tp_pessoa', models.PositiveSmallIntegerField(choices=[(0, 'Pessoa Física'), (1, 'Pessoa Jurídica')], default=0, help_text='Tipo de pessoa física (0), jurídica(1)')),
                ('fl_contribuinte_icms', models.PositiveSmallIntegerField(choices=[(0, 'Isento'), (1, 'Não Contribuinte'), (2, 'Contribuinte')], default=0, help_text='Contribuinte ICMS: isento (0) não contribuinte (1) contribuinte (2)')),
                ('nr_rg', models.CharField(help_text='Registro geral', max_length=15)),
                ('dc_orgao', models.CharField(blank=True, help_text='Órgão emissor', max_length=8, null=True)),
                ('dt_cadastro', models.DateField(auto_now_add=True, help_text='Data de cadastro do cliente no e-commerce')),
                ('nr_fone_residencia', models.PositiveIntegerField(blank=True, help_text='Telefone residencial', null=True)),
                ('nr_fone_celular', models.PositiveIntegerField(blank=True, help_text='Telefone celular', null=True)),
                ('nm_razao_social', models.CharField(help_text='Razão social para pessoa jurídica', max_length=128)),
                ('nr_inscricao_estadual', models.CharField(help_text='Inscrição estadual para pessoa jurídica', max_length=32)),
            ],
        ),
    ]
