# Generated by Django 2.1.3 on 2018-11-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20181109_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_produto', models.PositiveIntegerField(default=1, unique=True)),
                ('nm_produto', models.CharField(max_length=255, unique=True)),
                ('dc_modelo', models.CharField(max_length=64)),
                ('cd_barras', models.CharField(max_length=15)),
                ('cd_altura', models.DecimalField(decimal_places=8, max_digits=15)),
                ('nr_comprimento', models.DecimalField(decimal_places=8, max_digits=15)),
                ('nr_largura', models.DecimalField(decimal_places=8, max_digits=15)),
                ('nr_peso', models.DecimalField(decimal_places=8, max_digits=15)),
                ('dt_cadastro', models.DateField(auto_now_add=True)),
                ('fl_situacao', models.PositiveIntegerField(default=1)),
                ('cd_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_variacao', models.PositiveIntegerField(default=1)),
                ('dc_cor', models.PositiveIntegerField(default=1)),
                ('dc_numero', models.PositiveIntegerField(default=1)),
                ('dc_voltagem', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Produto')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Variacao')),
            ],
        ),
    ]
