# Generated by Django 2.1.3 on 2018-11-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_produto_variacao_variacaoproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='cd_marca',
            new_name='marca',
        ),
    ]
