# Generated by Django 2.1.3 on 2018-11-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181115_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_endereco_erp', models.PositiveIntegerField(help_text='Código do endereço no ERP')),
                ('nr_cep', models.CharField(help_text='Número do CEP', max_length=11)),
                ('dc_endereco', models.CharField(help_text='Descrição do endereço', max_length=128)),
                ('dc_numero', models.CharField(help_text='Número do endereço', max_length=9)),
                ('dc_complemento', models.CharField(help_text='Complemento', max_length=128)),
                ('dc_bairro', models.CharField(help_text='Bairro', max_length=128)),
                ('nm_cidade', models.CharField(help_text='Cidade', max_length=128)),
                ('sg_uf', models.CharField(help_text='UF do estado', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Cliente')),
            ],
        ),
    ]
