# Generated by Django 2.1.3 on 2018-11-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_pagamento', models.PositiveIntegerField(choices=[(0, 'Cartão'), (1, 'Boleto'), (2, 'Outros (Parcela)')], default=2, help_text='Cartão (0), Boleto (1), Outros (2) (Parcela)')),
                ('vl_transacao', models.DecimalField(decimal_places=4, help_text='Valor total das parcelas (Parcela)', max_digits=15)),
                ('vl_parcela', models.DecimalField(decimal_places=4, help_text='Valor da parcela (Parcela)', max_digits=15)),
                ('qt_parcelas', models.PositiveIntegerField(help_text='Quantidade de parcelas (Parcela)')),
                ('cd_nsu', models.CharField(blank=True, help_text='NSU quando usado cartão (Parcela)', max_length=16, null=True)),
                ('dt_transacao', models.DateField(auto_now_add=True)),
                ('cd_autorizacao', models.CharField(blank=True, help_text='Código da autorização quando usado cartão (Parcela)', max_length=16, null=True)),
                ('nm_bandeira', models.CharField(blank=True, help_text='Nome da bandeira quando usado cartão (Parcela)', max_length=16, null=True)),
                ('nr_pedido_gateway', models.CharField(blank=True, help_text='Número do pedido no gateway de pagamento (Parcela)', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_pedido_eco', models.PositiveIntegerField(help_text='Número do pedido no e-commerce')),
                ('nr_pedido_erp', models.PositiveIntegerField(help_text='Número do pedido no ERP')),
                ('dt_pedido', models.DateField(auto_now_add=True, help_text='Data do pedido')),
                ('hr_pedido', models.TimeField(auto_now_add=True, help_text='Hora do pedido')),
                ('cd_vendedor', models.PositiveIntegerField(help_text='Código do vendedor no ERP')),
                ('dc_observacao', models.TextField(help_text='Observação do cliente no pedido', max_length=230)),
                ('tp_entrega', models.PositiveIntegerField(choices=[(0, 'Retira'), (1, 'Entrega')], default=1, help_text='Retira (0), Entrega (1)')),
                ('vl_entrega', models.DecimalField(decimal_places=4, help_text='Valor da entrega', max_digits=15)),
                ('cliente', models.ForeignKey(help_text='Código do cliente no ERP', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Cliente')),
                ('filial', models.ForeignKey(help_text='Código da filial do pedido', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Filial')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_venda', models.DecimalField(decimal_places=4, help_text='Valor de venda (Produto)', max_digits=15)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='parcela',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Pedido'),
        ),
    ]
