# Generated by Django 2.1.3 on 2018-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_produto_hr_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='hr_cadastro',
        ),
        migrations.AlterField(
            model_name='produto',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
