# Generated by Django 2.1.3 on 2018-11-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20181116_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.Pedido'),
        ),
        migrations.DeleteModel(
            name='Parcela',
        ),
    ]
