# Generated by Django 2.1.3 on 2018-11-12 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20181110_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='hr_cadastro',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='dt_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
