# Generated by Django 2.1.3 on 2018-11-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_pedidoitem_qt_comprada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_pagamento', models.PositiveIntegerField(choices=[(0, 'Cartão'), (1, 'Boleto'), (2, 'Outros (Parcela)')], default=2, help_text='Cartão (0), Boleto (1), Outros (2) (Parcela)')),
                ('vl_transacao', models.DecimalField(decimal_places=4, help_text='Valor total das parcelas (Parcela)', max_digits=15)),
                ('vl_parcela', models.DecimalField(decimal_places=4, help_text='Valor da parcela (Parcela)', max_digits=15)),
                ('qt_parcelas', models.PositiveIntegerField(help_text='Quantidade de parcelas (Parcela)')),
                ('cd_nsu', models.CharField(blank=True, help_text='NSU quando usado cartão (Parcela)', max_length=16, null=True)),
                ('dt_transacao', models.DateField(auto_now_add=True)),
                ('cd_autorizacao', models.CharField(blank=True, help_text='Código da autorização quando usado cartão (Parcela)', max_length=16, null=True)),
                ('nm_bandeira', models.CharField(blank=True, help_text='Nome da bandeira quando usado cartão (Parcela)', max_length=16, null=True)),
                ('nm_adquirente', models.CharField(blank=True, help_text='Nome da adquirente quando usado cartão (Parcela)', max_length=16, null=True)),
                ('nr_pedido_gateway', models.CharField(blank=True, help_text='Número do pedido no gateway de pagamento (Parcela)', max_length=64, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='ecommerce.Pedido')),
            ],
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='qt_comprada',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Quantidade comprada (Produto)', max_digits=15),
        ),
    ]
