# Generated by Django 2.1.3 on 2018-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20181112_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dt_alteracao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='hr_alteracao',
            field=models.TimeField(auto_now=True),
        ),
    ]
